EDITOR=vim

# rasta prompt
PS1="\[\e]0;\u@\h \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;31m\][\u@\h]\[\033[00m\]\[\033[01;33m\]\$(__git_ps1 '[%s]')\[\033[00m\]\[\033[01;32m\][\w]\[\033[00m\] "
